import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/layouts/Header/Header";
import variables from './variables.module.scss'
import MenuMobile from "@/components/MenuMobile/MenuMobile";


export const metadata: Metadata = {
  title: "E-Cormerce Tech",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        <Header />
        <div className='app-responsive'>
          {children}
        </div>
        <MenuMobile />
      </body>
    </html>
  );
}
